# Generated by Django 2.0.7 on 2024-06-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20240607_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
    ]
