# Generated by Django 2.0.7 on 2024-06-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20240608_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
