# Generated by Django 2.0.7 on 2024-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20240614_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='image',
        ),
    ]
