# Generated by Django 2.0.7 on 2024-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20240614_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
