# Generated by Django 2.0.7 on 2024-06-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20240614_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
