# Generated by Django 2.0.7 on 2024-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20240614_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
