# Generated by Django 2.0.7 on 2024-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20240614_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
